sudo: false
language: node_js
node_js:
    # - "stable"
    - "0.12"
    # - 4.2

install:
    - npm install

script:
    - npm run test:ci

notifications:
    email:
        on_success: change
        on_failure: always
